#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

register:
    path: /api/register
    controller: App\Controller\RegisterController::register
    methods: ['POST']

user_list:
    path: /user
    controller: App\Controller\UserController::list
    methods: ['GET', 'POST']